FROM registry.redhat.io/ubi8/python-36:latest

USER root

# RUN dnf update -y
# RUN dnf -y groupinstall "Development Tools"
# RUN dnf install -y kernel-devel
# RUN dnf install -y wget

RUN dnf config-manager --add-repo=https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
RUN dnf -y install cuda

RUN dnf -y module reset nodejs
RUN dnf -y module install nodejs:14

RUN dnf clean all


USER 1001
