FROM registry.redhat.io/ubi8/python-38:latest

USER root

RUN dnf update -y
RUN dnf -y groupinstall "Development Tools"
RUN dnf install -y kernel-devel
RUN dnf install -y wget

RUN yum clean all


USER 1001
