kind: Template
apiVersion: v1
metadata:
  name: notebook-build
  annotations:
    openshift.io/display-name: JupyterHub (KeyCloak)
    iconClass: icon-python
    tags: python,jupyter
parameters:
  - name: APPLICATION_NAME
    value: jupyterhub
    required: true
  - name: NOTEBOOK_REPOSITORY_URL
    value: https://github.com/justindav1s/ai-on-openshift
    required: true
  - name: NOTEBOOK_REPOSITORY_CONTEXT_DIR
    value: 2_gpu_jupyter_notebook_build/tensorflow-notebook
    required: true
  - name: BASE_IMAGE
    value: quay.io/justindav1s/gpu-notebook-base:latest
    required: true
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-nb-img
      labels:
        app: ${APPLICATION_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}-nb-img
      labels:
        app: ${APPLICATION_NAME}
    spec:
      triggers:
        - type: ConfigChange
        - type: ImageChange
      source:
        type: Git
        git:
          uri: ${NOTEBOOK_REPOSITORY_URL}
        contextDir: ${NOTEBOOK_REPOSITORY_CONTEXT_DIR}
        secrets:
          - secret:
              name: ${APPLICATION_NAME}-nb
            destinationDir: /tmp/build
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: "DockerImage"
            name: ${BASE_IMAGE}
          env:
            - name: JUPYTER_MASTER_FILES
              value: /opt/app-root/master
      output:
        to:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}-nb-img:latest
      resources:
        limits:
          memory: 3Gi    