apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jupyter-tensorflow
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: tensorflow
    name: tensorflow
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tensorflow
      deploymentconfig: tensorflow
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: tensorflow
          deploymentconfig: tensorflow
      spec:
        serviceAccountName: tensorflowuser
        containers:
        - name: tensorflow
          image: "jupyter/tensorflow-notebook"
          imagePullPolicy: Always
          securityContext:
            privileged: true
          command: ["jupyter"]
          args: ["notebook", "--allow-root"]
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    name: tensorflow
    labels:
      app: tensorflow
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8888
    selector:
      app: tensorflow
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: tensorflow
    name: tensorflow
  spec:
    port:
      targetPort: 8888
    to:
      kind: Service
      name: tensorflow
      weight: 100
    wildcardPolicy: None