apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: jupyter-tensorflow-gpu
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: tensorflow-gpu
    name: tensorflow-gpu
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: tensorflow-gpu
      deploymentconfig: tensorflow-gpu
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: tensorflow-gpu
          deploymentconfig: tensorflow-gpu
      spec:
        serviceAccountName: tensorflowuser
        containers:
        - name: tensorflow-gpu
          image: "tensorflow/tensorflow:1.13.2-gpu-py3-jupyter"
          imagePullPolicy: Always
          securityContext:
            privileged: true
#          command: ["jupyter"]
#          args: ["notebook", "--allow-root"]
          resources:
            limits:
              nvidia.com/gpu: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    name: tensorflow-gpu
    labels:
      app: tensorflow-gpu
  spec:
    ports:
    - name: http
      protocol: TCP
      port: 8888
    selector:
      app: tensorflow-gpu
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: tensorflow-gpu
    name: tensorflow-gpu
  spec:
    port:
      targetPort: 8888
    to:
      kind: Service
      name: tensorflow-gpu
      weight: 100
    wildcardPolicy: None
