kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: jupyterhub-builder
  annotations:
    openshift.io/display-name: JupyterHub Builder
    description: Template for building a JupyterHub image.
    iconClass: icon-python
    tags: python,jupyter,jupyterhub
objects:

- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: jupyterhub
    labels:
      build: jupyterhub
  spec:
    lookupPolicy:
      local: true

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: jupyterhub-bc
    labels:
      build: jupyterhub
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      type: Git
      git:
        uri: https://github.com/jupyter-on-openshift/jupyterhub-quickstart.git
        ref: ${VERSION}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python:3.6
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: jupyterhub:${VERSION}

parameters:
- name: VERSION
  value: "3.1.0"
  required: true
